services:
  backend:
    container_name: backend
    image: backend:latest
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
      platforms:
        - "linux/arm64/v8"
    ports:
      - '3001:3001'
  frontend:
    container_name: frontend
    image: frontend:latest
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
      platforms:
        - "linux/arm64/v8"
    ports:
      - '3000:3000'
    depends_on:
      - backend