services:
  backend:
    container_name: backend
    image: backend:latest
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
      platforms:
        - "linux/arm64/v8"
    ports:
      - '3001:3001'
  frontend:
    container_name: frontend
    image: frontend:latest
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
      platforms:
        - "linux/arm64/v8"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./apps/frontend/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend

volumes:
  caddy_data:
  caddy_config: